In [1]:
import geopandas as gpd
import pandas as pd

In [2]:
unfaelle = gpd.read_file(r'C:\Users\leoni\Documents\HSLU\5. Semester\Informationsvisualisierung\Einzelprojekt\informationsvisualisierung-leonid-wouters\Daten\RoadTrafficAccidentLocations.json')

In [5]:
unfaelle.info()

<class 'geopandas.geodataframe.GeoDataFrame'>
RangeIndex: 232303 entries, 0 to 232302
Data columns (total 37 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   AccidentUID                  232303 non-null  object
 1   AccidentType                 232303 non-null  object
 2   AccidentType_de              232303 non-null  object
 3   AccidentType_fr              232303 non-null  object
 4   AccidentType_it              232303 non-null  object
 5   AccidentType_en              232303 non-null  object
 6   AccidentSeverityCategory     232303 non-null  object
 7   AccidentSeverityCategory_de  232303 non-null  object
 8   AccidentSeverityCategory_fr  232303 non-null  object
 9   AccidentSeverityCategory_it  232303 non-null  object
 10  AccidentSeverityCategory_en  232303 non-null  object
 11  AccidentInvolvingPedestrian  232303 non-null  object
 12  AccidentInvolvingBicycle     232303 non-null  object
 13  AccidentInvolvingMotorcycle  232303 non-null  object
 14  RoadType                     232303 non-null  object
 15  RoadType_de                  232303 non-null  object
 16  RoadType_fr                  232303 non-null  object
 17  RoadType_it                  232303 non-null  object
 18  RoadType_en                  232303 non-null  object
 19  AccidentLocation_CHLV95_E    232303 non-null  object
 20  AccidentLocation_CHLV95_N    232303 non-null  object
 21  CantonCode                   232303 non-null  object
 22  MunicipalityCode             232303 non-null  object
 23  AccidentYear                 232303 non-null  object
 24  AccidentMonth                232303 non-null  object
 25  AccidentMonth_de             232303 non-null  object
 26  AccidentMonth_fr             232303 non-null  object
 27  AccidentMonth_it             232303 non-null  object
 28  AccidentMonth_en             232303 non-null  object
 29  AccidentWeekDay              232303 non-null  object
 30  AccidentWeekDay_de           232303 non-null  object
 31  AccidentWeekDay_fr           232303 non-null  object
 32  AccidentWeekDay_it           232303 non-null  object
 33  AccidentWeekDay_en           232303 non-null  object
 34  AccidentHour                 232303 non-null  object
 35  AccidentHour_text            232303 non-null  object
 36  geometry                     232303 non-null  geometry
dtypes: geometry(1), object(36)
memory usage: 65.6+ MB

In [9]:
# Behalte nur Daten aus dem Jahr 2015-2023 mit String
unfaelle = unfaelle[unfaelle['AccidentYear'].str.contains('2015|2016|2017|2018|2019|2020|2021|2022|2023')]

In [11]:
# Behalte nur die Folgenden Spalten: 'AccidentUID','AccidentType_de', 'AccidentSeverityCategory_de', 'AccidentInvolvingPedestrian', 'AccidentInvolvingBicycle', 'AccidentInvolvingMotorcycle', 'RoadType_de', 'AccidentLocation_CHLV95_E', 'AccidentLocation_CHLV95_N', 'CantonCode', 'MunicipalityCode', 'AccidentYear', 'AccidentMonth_de', 'AccidentWeekDay_de', 'AccidentHour', 'AccidentHour_text', 'geometry'
unfaelle_bereinigt = unfaelle[['AccidentUID','AccidentType_de', 'AccidentSeverityCategory_de', 'AccidentInvolvingPedestrian', 'AccidentInvolvingBicycle', 'AccidentInvolvingMotorcycle', 'RoadType_de', 'AccidentLocation_CHLV95_E', 'AccidentLocation_CHLV95_N', 'CantonCode', 'MunicipalityCode', 'AccidentYear', 'AccidentMonth_de', 'AccidentWeekDay_de', 'AccidentHour', 'AccidentHour_text', 'geometry']]

In [12]:
# Behalte nur Einträge für den Kanton Zürich
unfaelle_bereinigt = unfaelle_bereinigt[unfaelle_bereinigt['CantonCode'] == 'ZH']

In [13]:
unfaelle_bereinigt.head()

,AccidentUID,AccidentType_de,AccidentSeverityCategory_de,AccidentInvolvingPedestrian,AccidentInvolvingBicycle,AccidentInvolvingMotorcycle,RoadType_de,AccidentLocation_CHLV95_E,AccidentLocation_CHLV95_N,CantonCode,MunicipalityCode,AccidentYear,AccidentMonth_de,AccidentWeekDay_de,AccidentHour,AccidentHour_text,geometry
14996,299BEA452ABC01A4E0530A8394271314,Auffahrunfall,Unfall mit Leichtverletzten,false,false,false,Nebenstrasse,2690309,1239212,ZH,0152,2016,Januar,Donnerstag,14,14h-15h,POINT Z (8.63269 47.29761 0.00000)
14997,29AE4942C84E018CE0530A839427A873,Auffahrunfall,Unfall mit Schwerverletzten,false,false,false,Autobahn,2692825,1250244,ZH,0199,2016,Januar,Donnerstag,13,13h-14h,POINT Z (8.66824 47.39648 0.00000)
15001,29EFBD2A994C0134E0530A83942760E8,Auffahrunfall,Unfall mit Leichtverletzten,false,false,false,Hauptstrasse,2689131,1252238,ZH,0054,2016,Januar,Mittwoch,18,18h-19h,POINT Z (8.61971 47.41492 0.00000)
15009,2A26173317E90068E0530A8394271BBF,Überqueren der Fahrbahn,Unfall mit Leichtverletzten,false,false,false,Nebenstrasse,2680937,1273117,ZH,0071,2016,Januar,Donnerstag,19,19h-20h,POINT Z (8.51494 47.60374 0.00000)
15011,2A28E2E05DC801D6E0530A839427ED82,Schleuder- oder Selbstunfall,Unfall mit Leichtverletzten,false,false,false,Hauptstrasse,2688474,1264056,ZH,0056,2016,Januar,Sonntag,13,13h-14h,POINT Z (8.61335 47.52129 0.00000)

In [14]:
# Umbenennen der Spalten
unfaelle_bereinigt = unfaelle_bereinigt.rename(columns={'AccidentUID': 'UnfallID',
                                                        'AccidentType_de': 'Unfallart',
                                                        'AccidentSeverityCategory_de': 'Unfallschwere',
                                                        'AccidentInvolvingPedestrian': 'Fussgänger_beteiligt',
                                                        'AccidentInvolvingBicycle': 'Fahrrad_beteiligt',
                                                        'AccidentInvolvingMotorcycle': 'Motorrad_beteiligt',
                                                        'RoadType_de': 'Strassentyp',
                                                        'AccidentLocation_CHLV95_E': 'Unfallort_Lon',
                                                        'AccidentLocation_CHLV95_N': 'Unfallort_Lat',
                                                        'CantonCode': 'Kanton',
                                                        'MunicipalityCode': 'Gemeinde',
                                                        'AccidentYear': 'Jahr',
                                                        'AccidentMonth_de': 'Monat',
                                                        'AccidentWeekDay_de': 'Wochentag',
                                                        'AccidentHour': 'Stunde',
                                                        'AccidentHour_text': 'Stunde_text',})

In [15]:
# Behalte nur Einträge mit der Gemeinde 0261
unfaelle_bereinigt = unfaelle_bereinigt[unfaelle_bereinigt['Gemeinde'] == '0261']

In [16]:
unfaelle_bereinigt

,UnfallID,Unfallart,Unfallschwere,Fussgänger_beteiligt,Fahrrad_beteiligt,Motorrad_beteiligt,Strassentyp,Unfallort_Lon,Unfallort_Lat,Kanton,Gemeinde,Jahr,Monat,Wochentag,Stunde,Stunde_text,geometry
15028,2AF2FBACB62B00DAE0530A8394273CC3,Fussgängerunfall,Unfall mit Leichtverletzten,true,true,false,Nebenstrasse,2681186,1247896,ZH,0261,2016,Januar,Mittwoch,16,16h-17h,POINT Z (8.51365 47.37690 0.00000)
15034,2B51E1C5A119015CE0530A839427323A,Schleuder- oder Selbstunfall,Unfall mit Leichtverletzten,false,true,false,Hauptstrasse,2682739,1244360,ZH,0261,2016,Januar,Freitag,13,13h-14h,POINT Z (8.53356 47.34490 0.00000)
15055,2C6EC4B16319006EE0530A8394275C3E,Schleuder- oder Selbstunfall,Unfall mit Leichtverletzten,false,true,false,Nebenstrasse,2683598,1248099,ZH,0261,2016,Februar,Samstag,19,19h-20h,POINT Z (8.54563 47.37842 0.00000)
15129,2F5393B75558017AE0530A839427C6B4,Auffahrunfall,Unfall mit Leichtverletzten,false,false,false,Hauptstrasse,2682564,1251648,ZH,0261,2016,März,Freitag,17,17h-18h,POINT Z (8.53259 47.41047 0.00000)
15136,303090D5AB8300A8E0530A83942731D6,Auffahrunfall,Unfall mit Leichtverletzten,false,false,false,Hauptstrasse,2685438,1251781,ZH,0261,2016,Januar,Donnerstag,10,10h-11h,POINT Z (8.57069 47.41130 0.00000)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
232236,FADB4DEF49E101DCE0530AB38B0228F8,Auffahrunfall,Unfall mit Schwerverletzten,false,true,false,Nebenstrasse,2683091,1247989,ZH,0261,2023,April,Donnerstag,06,06h-07h,POINT Z (8.53889 47.37750 0.00000)
232243,FB690AF97A6D0174E0530AB38B02B387,Überqueren der Fahrbahn,Unfall mit Leichtverletzten,false,true,false,Nebenstrasse,2684492,1245924,ZH,0261,2023,Mai,Mittwoch,16,16h-17h,POINT Z (8.55705 47.35875 0.00000)
232250,FC425F09B9320124E0530AB38B029ECF,Fussgängerunfall,Unfall mit Leichtverletzten,true,false,false,Nebenstrasse,2683300,1251438,ZH,0261,2023,April,Dienstag,08,08h-09h,POINT Z (8.54230 47.40849 0.00000)
232253,FC436832B6E201D4E0530AB38B0280E4,Abbiegeunfall,Unfall mit Leichtverletzten,false,false,false,Hauptstrasse,2683625,1251449,ZH,0261,2023,Mai,Sonntag,13,13h-14h,POINT Z (8.54661 47.40855 0.00000)
232270,FD7276FD9C8C019CE0530AB38B0232BA,Fussgängerunfall,Unfall mit Leichtverletzten,false,false,false,Nebenstrasse,2680809,1245990,ZH,0261,2023,Mai,Mittwoch,15,15h-16h,POINT Z (8.50832 47.35980 0.00000)

In [17]:
unfaelle_bereinigt

,UnfallID,Unfallart,Unfallschwere,Fussgänger_beteiligt,Fahrrad_beteiligt,Motorrad_beteiligt,Strassentyp,Unfallort_Lon,Unfallort_Lat,Kanton,Gemeinde,Jahr,Monat,Wochentag,Stunde,Stunde_text,geometry
15028,2AF2FBACB62B00DAE0530A8394273CC3,Fussgängerunfall,Unfall mit Leichtverletzten,true,true,false,Nebenstrasse,2681186,1247896,ZH,0261,2016,Januar,Mittwoch,16,16h-17h,POINT Z (8.51365 47.37690 0.00000)
15034,2B51E1C5A119015CE0530A839427323A,Schleuder- oder Selbstunfall,Unfall mit Leichtverletzten,false,true,false,Hauptstrasse,2682739,1244360,ZH,0261,2016,Januar,Freitag,13,13h-14h,POINT Z (8.53356 47.34490 0.00000)
15055,2C6EC4B16319006EE0530A8394275C3E,Schleuder- oder Selbstunfall,Unfall mit Leichtverletzten,false,true,false,Nebenstrasse,2683598,1248099,ZH,0261,2016,Februar,Samstag,19,19h-20h,POINT Z (8.54563 47.37842 0.00000)
15129,2F5393B75558017AE0530A839427C6B4,Auffahrunfall,Unfall mit Leichtverletzten,false,false,false,Hauptstrasse,2682564,1251648,ZH,0261,2016,März,Freitag,17,17h-18h,POINT Z (8.53259 47.41047 0.00000)
15136,303090D5AB8300A8E0530A83942731D6,Auffahrunfall,Unfall mit Leichtverletzten,false,false,false,Hauptstrasse,2685438,1251781,ZH,0261,2016,Januar,Donnerstag,10,10h-11h,POINT Z (8.57069 47.41130 0.00000)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
232236,FADB4DEF49E101DCE0530AB38B0228F8,Auffahrunfall,Unfall mit Schwerverletzten,false,true,false,Nebenstrasse,2683091,1247989,ZH,0261,2023,April,Donnerstag,06,06h-07h,POINT Z (8.53889 47.37750 0.00000)
232243,FB690AF97A6D0174E0530AB38B02B387,Überqueren der Fahrbahn,Unfall mit Leichtverletzten,false,true,false,Nebenstrasse,2684492,1245924,ZH,0261,2023,Mai,Mittwoch,16,16h-17h,POINT Z (8.55705 47.35875 0.00000)
232250,FC425F09B9320124E0530AB38B029ECF,Fussgängerunfall,Unfall mit Leichtverletzten,true,false,false,Nebenstrasse,2683300,1251438,ZH,0261,2023,April,Dienstag,08,08h-09h,POINT Z (8.54230 47.40849 0.00000)
232253,FC436832B6E201D4E0530AB38B0280E4,Abbiegeunfall,Unfall mit Leichtverletzten,false,false,false,Hauptstrasse,2683625,1251449,ZH,0261,2023,Mai,Sonntag,13,13h-14h,POINT Z (8.54661 47.40855 0.00000)
232270,FD7276FD9C8C019CE0530AB38B0232BA,Fussgängerunfall,Unfall mit Leichtverletzten,false,false,false,Nebenstrasse,2680809,1245990,ZH,0261,2023,Mai,Mittwoch,15,15h-16h,POINT Z (8.50832 47.35980 0.00000)

In [18]:
unfaelle_bereinigt.to_file(r'C:\Users\leoni\Documents\HSLU\5. Semester\Informationsvisualisierung\Einzelprojekt\informationsvisualisierung-leonid-wouters\Daten\unfaelle_zuerich_2023.json', driver='GeoJSON')