In [25]:
import geopandas as gpd
import pandas as pd

In [26]:
unfaelle = gpd.read_file(r"C:\Users\leoni\Documents\HSLU\5. Semester\Informationsvisualisierung\Einzelprojekt\informationsvisualisierung-leonid-wouters\Daten\unfaelle_zuerich_2023.json")

In [27]:
unfaelle.head()

,UnfallID,Unfallart,Unfallschwere,Fussgänger_beteiligt,Fahrrad_beteiligt,Motorrad_beteiligt,Strassentyp,Unfallort_Lon,Unfallort_Lat,Kanton,Gemeinde,Jahr,Monat,Wochentag,Stunde,Stunde_text,geometry
0,2AF2FBACB62B00DAE0530A8394273CC3,Fussgängerunfall,Unfall mit Leichtverletzten,true,true,false,Nebenstrasse,2681186,1247896,ZH,0261,2016,Januar,Mittwoch,16,16h-17h,POINT Z (8.51365 47.37690 0.00000)
1,2B51E1C5A119015CE0530A839427323A,Schleuder- oder Selbstunfall,Unfall mit Leichtverletzten,false,true,false,Hauptstrasse,2682739,1244360,ZH,0261,2016,Januar,Freitag,13,13h-14h,POINT Z (8.53356 47.34490 0.00000)
2,2C6EC4B16319006EE0530A8394275C3E,Schleuder- oder Selbstunfall,Unfall mit Leichtverletzten,false,true,false,Nebenstrasse,2683598,1248099,ZH,0261,2016,Februar,Samstag,19,19h-20h,POINT Z (8.54563 47.37842 0.00000)
3,2F5393B75558017AE0530A839427C6B4,Auffahrunfall,Unfall mit Leichtverletzten,false,false,false,Hauptstrasse,2682564,1251648,ZH,0261,2016,März,Freitag,17,17h-18h,POINT Z (8.53259 47.41047 0.00000)
4,303090D5AB8300A8E0530A83942731D6,Auffahrunfall,Unfall mit Leichtverletzten,false,false,false,Hauptstrasse,2685438,1251781,ZH,0261,2016,Januar,Donnerstag,10,10h-11h,POINT Z (8.57069 47.41130 0.00000)

In [28]:
unfaelle.info()

<class 'geopandas.geodataframe.GeoDataFrame'>
RangeIndex: 11689 entries, 0 to 11688
Data columns (total 17 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   UnfallID              11689 non-null  object
 1   Unfallart             11689 non-null  object
 2   Unfallschwere         11689 non-null  object
 3   Fussgänger_beteiligt  11689 non-null  object
 4   Fahrrad_beteiligt     11689 non-null  object
 5   Motorrad_beteiligt    11689 non-null  object
 6   Strassentyp           11689 non-null  object
 7   Unfallort_Lon         11689 non-null  object
 8   Unfallort_Lat         11689 non-null  object
 9   Kanton                11689 non-null  object
 10  Gemeinde              11689 non-null  object
 11  Jahr                  11689 non-null  object
 12  Monat                 11689 non-null  object
 13  Wochentag             11689 non-null  object
 14  Stunde                11689 non-null  object
 15  Stunde_text           11689 non-null  object
 16  geometry              11689 non-null  geometry
dtypes: geometry(1), object(16)
memory usage: 1.5+ MB

In [29]:
import plotly.express as px

fig = px.scatter_mapbox(unfaelle, lat=unfaelle.geometry.y, lon=unfaelle.geometry.x, color='Unfallschwere', zoom=10)
fig.update_layout(
    mapbox_style="open-street-map",
    width=600,
    height=600,
    legend=dict(
        x=0.01,  # Positioniert die Legende innerhalb der Karte
        y=0.99,  # nahe dem oberen Rand
        bgcolor="rgba(255, 255, 255, 0.8)"  # Halbtransparenter Hintergrund für bessere Lesbarkeit
    )
)
fig.show()

In [30]:
tempo = gpd.read_file(r"C:\Users\leoni\Documents\HSLU\5. Semester\Informationsvisualisierung\Einzelprojekt\informationsvisualisierung-leonid-wouters\Daten\stadt_zuerich_signalisierte_geschwindigkeiten.geojson")

In [31]:
tempo.head()

,ausnahmen_fahrverbot,fahrverbot_ssv,id,lokalisationsname,objectid,publiziert_vsi_datum,rechtskraeftig_datum,temporegime,temporegime_technical,umgesetzt_datum,geometry
0,None,None,4465,Elias-Canetti-Strasse,218.0,NaT,NaT,T30,T30,2019-10-16,"MULTILINESTRING ((8.54099 47.41177, 8.54029 47..."
1,None,None,4483,Laubiweg,219.0,NaT,NaT,Fahrverbot,T0,NaT,"MULTILINESTRING ((8.53389 47.39337, 8.53430 47..."
2,None,None,4510,Batteriestrasse,220.0,NaT,NaT,Fahrverbot,T0,NaT,"MULTILINESTRING ((8.55283 47.38901, 8.55284 47..."
3,None,None,4555,Hegianwandweg,221.0,NaT,NaT,Fahrverbot,T0,NaT,"MULTILINESTRING ((8.50661 47.35495, 8.50644 47..."
4,None,None,4598,Ettenfeldstrasse,222.0,NaT,NaT,T20,T20,2020-07-30,"MULTILINESTRING ((8.55279 47.42198, 8.55341 47..."

In [32]:
tempo.info()

<class 'geopandas.geodataframe.GeoDataFrame'>
RangeIndex: 5225 entries, 0 to 5224
Data columns (total 11 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   ausnahmen_fahrverbot   28 non-null     object
 1   fahrverbot_ssv         63 non-null     object
 2   id                     5225 non-null   int64
 3   lokalisationsname      5225 non-null   object
 4   objectid               5225 non-null   float64
 5   publiziert_vsi_datum   138 non-null    datetime64[ns]
 6   rechtskraeftig_datum   143 non-null    datetime64[ns]
 7   temporegime            5225 non-null   object
 8   temporegime_technical  5225 non-null   object
 9   umgesetzt_datum        622 non-null    datetime64[ns]
 10  geometry               5225 non-null   geometry
dtypes: datetime64[ns](3), float64(1), geometry(1), int64(1), object(5)
memory usage: 449.1+ KB

In [33]:
# Lösche alle Spalten, die nicht benötigt werden
tempo = tempo.drop(columns=['ausnahmen_fahrverbot', 'fahrverbot_ssv', 'id','objectid', 'publiziert_vsi_datum', 'rechtskraeftig_datum', 'temporegime_technical', 'umgesetzt_datum'])

In [34]:
tempo.head()

,lokalisationsname,temporegime,geometry
0,Elias-Canetti-Strasse,T30,"MULTILINESTRING ((8.54099 47.41177, 8.54029 47..."
1,Laubiweg,Fahrverbot,"MULTILINESTRING ((8.53389 47.39337, 8.53430 47..."
2,Batteriestrasse,Fahrverbot,"MULTILINESTRING ((8.55283 47.38901, 8.55284 47..."
3,Hegianwandweg,Fahrverbot,"MULTILINESTRING ((8.50661 47.35495, 8.50644 47..."
4,Ettenfeldstrasse,T20,"MULTILINESTRING ((8.55279 47.42198, 8.55341 47..."

In [35]:
# Lösche alle Einträge, die Fahrverbote enthalten
tempo = tempo[tempo['temporegime'] != 'Fahrverbot']

In [36]:
# Füge dem unfaelle Datensatz eine Spalte 'Temporegime' hinzu
unfaelle['Temporegime'] = None

In [37]:
from shapely.geometry import Point
# Wandle die Geometrie in 2D um, indem nur die x- und y-Koordinaten verwendet werden
unfaelle['geometry'] = unfaelle['geometry'].apply(lambda geom: Point(geom.x, geom.y))

# Setze die Geometrie auf den neuen 2D-Punkt
unfaelle = gpd.GeoDataFrame(unfaelle, geometry='geometry')

In [38]:
unfaelle.head(2)

,UnfallID,Unfallart,Unfallschwere,Fussgänger_beteiligt,Fahrrad_beteiligt,Motorrad_beteiligt,Strassentyp,Unfallort_Lon,Unfallort_Lat,Kanton,Gemeinde,Jahr,Monat,Wochentag,Stunde,Stunde_text,geometry,Temporegime
0,2AF2FBACB62B00DAE0530A8394273CC3,Fussgängerunfall,Unfall mit Leichtverletzten,true,true,false,Nebenstrasse,2681186,1247896,ZH,0261,2016,Januar,Mittwoch,16,16h-17h,POINT (8.51365 47.37690),None
1,2B51E1C5A119015CE0530A839427323A,Schleuder- oder Selbstunfall,Unfall mit Leichtverletzten,false,true,false,Hauptstrasse,2682739,1244360,ZH,0261,2016,Januar,Freitag,13,13h-14h,POINT (8.53356 47.34490),None

In [39]:
tempo.head(2)

,lokalisationsname,temporegime,geometry
0,Elias-Canetti-Strasse,T30,"MULTILINESTRING ((8.54099 47.41177, 8.54029 47..."
4,Ettenfeldstrasse,T20,"MULTILINESTRING ((8.55279 47.42198, 8.55341 47..."

In [40]:
unfaelle = unfaelle.set_crs(epsg=4326)

In [41]:
import geopandas as gpd
from shapely.ops import nearest_points

# Stelle sicher, dass unfaelle und tempo dasselbe Koordinatensystem verwenden
unfaelle = unfaelle.to_crs(tempo.crs)

# Funktion zum Finden des nächstgelegenen Temporegimes für jeden Unfall
def find_nearest_temporegime(unfall_geom):
    nearest_line = tempo.geometry.unary_union
    nearest_point = nearest_points(unfall_geom, nearest_line)[1]
    
    # Suche nach der Linie, die dem nächstgelegenen Punkt entspricht
    nearest = tempo.distance(nearest_point).idxmin()
    return tempo.loc[nearest, 'temporegime']

# Füge das Temporegime zu den Unfällen hinzu
unfaelle['Temporegime'] = unfaelle.geometry.apply(find_nearest_temporegime)

# Ergebnisse überprüfen
unfaelle.head()

C:\Users\leoni\AppData\Local\Temp\ipykernel_20116\2288156039.py:13: UserWarning:

Geometry is in a geographic CRS. Results from 'distance' are likely incorrect. Use 'GeoSeries.to_crs()' to re-project geometries to a projected CRS before this operation.


c:\Users\leoni\anaconda3\lib\site-packages\shapely\measurement.py:74: RuntimeWarning:

invalid value encountered in distance

C:\Users\leoni\AppData\Local\Temp\ipykernel_20116\2288156039.py:13: UserWarning:

Geometry is in a geographic CRS. Results from 'distance' are likely incorrect. Use 'GeoSeries.to_crs()' to re-project geometries to a projected CRS before this operation.


c:\Users\leoni\anaconda3\lib\site-packages\shapely\measurement.py:74: RuntimeWarning:

invalid value encountered in distance

C:\Users\leoni\AppData\Local\Temp\ipykernel_20116\2288156039.py:13: UserWarning:

Geometry is in a geographic CRS. Results from 'distance' are likely incorrect. Use 'GeoSeries.to_crs()' to re-project geometries to a projected CRS before this operation.


c:\Users\leoni\anaconda3\lib\site-packages\shapely\measurement.py:74: RuntimeWarning:

invalid value encountered in distance

C:\Users\leoni\AppData\Local\Temp\ipykernel_20116\2288156039.py:13: UserWarning:

Geometry is in a geographic CRS. Results from 'distance' are likely incorrect. Use 'GeoSeries.to_crs()' to re-project geometries to a projected CRS before this operation.


c:\Users\leoni\anaconda3\lib\site-packages\shapely\measurement.py:74: RuntimeWarning:

invalid value encountered in distance

C:\Users\leoni\AppData\Local\Temp\ipykernel_20116\2288156039.py:13: UserWarning:

Geometry is in a geographic CRS. Results from 'distance' are likely incorrect. Use 'GeoSeries.to_crs()' to re-project geometries to a projected CRS before this operation.


c:\Users\leoni\anaconda3\lib\site-packages\shapely\measurement.py:74: RuntimeWarning:

invalid value encountered in distance

C:\Users\leoni\AppData\Local\Temp\ipykernel_20116\2288156039.py:13: UserWarning:

Geometry is in a geographic CRS. Results from 'distance' are likely incorrect. Use 'GeoSeries.to_crs()' to re-project geometries to a projected CRS before this operation.


c:\Users\leoni\anaconda3\lib\site-packages\shapely\measurement.py:74: RuntimeWarning:

invalid value encountered in distance

C:\Users\leoni\AppData\Local\Temp\ipykernel_20116\2288156039.py:13: UserWarning:

Geometry is in a geographic CRS. Results from 'distance' are likely incorrect. Use 'GeoSeries.to_crs()' to re-project geometries to a projected CRS before this operation.


c:\Users\leoni\anaconda3\lib\site-packages\shapely\measurement.py:74: RuntimeWarning:

invalid value encountered in distance

C:\Users\leoni\AppData\Local\Temp\ipykernel_20116\2288156039.py:13: UserWarning:

Geometry is in a geographic CRS. Results from 'distance' are likely incorrect. Use 'GeoSeries.to_crs()' to re-project geometries to a projected CRS before this operation.


c:\Users\leoni\anaconda3\lib\site-packages\shapely\measurement.py:74: RuntimeWarning:

invalid value encountered in distance

C:\Users\leoni\AppData\Local\Temp\ipykernel_20116\2288156039.py:13: UserWarning:

Geometry is in a geographic CRS. Results from 'distance' are likely incorrect. Use 'GeoSeries.to_crs()' to re-project geometries to a projected CRS before this operation.


c:\Users\leoni\anaconda3\lib\site-packages\shapely\measurement.py:74: RuntimeWarning:

invalid value encountered in distance

C:\Users\leoni\AppData\Local\Temp\ipykernel_20116\2288156039.py:13: UserWarning:

Geometry is in a geographic CRS. Results from 'distance' are likely incorrect. Use 'GeoSeries.to_crs()' to re-project geometries to a projected CRS before this operation.


c:\Users\leoni\anaconda3\lib\site-packages\shapely\measurement.py:74: RuntimeWarning:

invalid value encountered in distance

C:\Users\leoni\AppData\Local\Temp\ipykernel_20116\2288156039.py:13: UserWarning:

Geometry is in a geographic CRS. Results from 'distance' are likely incorrect. Use 'GeoSeries.to_crs()' to re-project geometries to a projected CRS before this operation.


c:\Users\leoni\anaconda3\lib\site-packages\shapely\measurement.py:74: RuntimeWarning:

invalid value encountered in distance

C:\Users\leoni\AppData\Local\Temp\ipykernel_20116\2288156039.py:13: UserWarning:

Geometry is in a geographic CRS. Results from 'distance' are likely incorrect. Use 'GeoSeries.to_crs()' to re-project geometries to a projected CRS before this operation.


c:\Users\leoni\anaconda3\lib\site-packages\shapely\measurement.py:74: RuntimeWarning:

invalid value encountered in distance

C:\Users\leoni\AppData\Local\Temp\ipykernel_20116\2288156039.py:13: UserWarning:

Geometry is in a geographic CRS. Results from 'distance' are likely incorrect. Use 'GeoSeries.to_crs()' to re-project geometries to a projected CRS before this operation.


c:\Users\leoni\anaconda3\lib\site-packages\shapely\measurement.py:74: RuntimeWarning:

invalid value encountered in distance

C:\Users\leoni\AppData\Local\Temp\ipykernel_20116\2288156039.py:13: UserWarning:

Geometry is in a geographic CRS. Results from 'distance' are likely incorrect. Use 'GeoSeries.to_crs()' to re-project geometries to a projected CRS before this operation.


c:\Users\leoni\anaconda3\lib\site-packages\shapely\measurement.py:74: RuntimeWarning:

invalid value encountered in distance

C:\Users\leoni\AppData\Local\Temp\ipykernel_20116\2288156039.py:13: UserWarning:

Geometry is in a geographic CRS. Results from 'distance' are likely incorrect. Use 'GeoSeries.to_crs()' to re-project geometries to a projected CRS before this operation.


c:\Users\leoni\anaconda3\lib\site-packages\shapely\measurement.py:74: RuntimeWarning:

invalid value encountered in distance

C:\Users\leoni\AppData\Local\Temp\ipykernel_20116\2288156039.py:13: UserWarning:

Geometry is in a geographic CRS. Results from 'distance' are likely incorrect. Use 'GeoSeries.to_crs()' to re-project geometries to a projected CRS before this operation.


c:\Users\leoni\anaconda3\lib\site-packages\shapely\measurement.py:74: RuntimeWarning:

invalid value encountered in distance

C:\Users\leoni\AppData\Local\Temp\ipykernel_20116\2288156039.py:13: UserWarning:

Geometry is in a geographic CRS. Results from 'distance' are likely incorrect. Use 'GeoSeries.to_crs()' to re-project geometries to a projected CRS before this operation.


c:\Users\leoni\anaconda3\lib\site-packages\shapely\measurement.py:74: RuntimeWarning:

invalid value encountered in distance

C:\Users\leoni\AppData\Local\Temp\ipykernel_20116\2288156039.py:13: UserWarning:

Geometry is in a geographic CRS. Results from 'distance' are likely incorrect. Use 'GeoSeries.to_crs()' to re-project geometries to a projected CRS before this operation.


c:\Users\leoni\anaconda3\lib\site-packages\shapely\measurement.py:74: RuntimeWarning:

invalid value encountered in distance

C:\Users\leoni\AppData\Local\Temp\ipykernel_20116\2288156039.py:13: UserWarning:

Geometry is in a geographic CRS. Results from 'distance' are likely incorrect. Use 'GeoSeries.to_crs()' to re-project geometries to a projected CRS before this operation.


c:\Users\leoni\anaconda3\lib\site-packages\shapely\measurement.py:74: RuntimeWarning:

invalid value encountered in distance

C:\Users\leoni\AppData\Local\Temp\ipykernel_20116\2288156039.py:13: UserWarning:

Geometry is in a geographic CRS. Results from 'distance' are likely incorrect. Use 'GeoSeries.to_crs()' to re-project geometries to a projected CRS before this operation.


c:\Users\leoni\anaconda3\lib\site-packages\shapely\measurement.py:74: RuntimeWarning:

invalid value encountered in distance

C:\Users\leoni\AppData\Local\Temp\ipykernel_20116\2288156039.py:13: UserWarning:

Geometry is in a geographic CRS. Results from 'distance' are likely incorrect. Use 'GeoSeries.to_crs()' to re-project geometries to a projected CRS before this operation.


c:\Users\leoni\anaconda3\lib\site-packages\shapely\measurement.py:74: RuntimeWarning:

invalid value encountered in distance

C:\Users\leoni\AppData\Local\Temp\ipykernel_20116\2288156039.py:13: UserWarning:

Geometry is in a geographic CRS. Results from 'distance' are likely incorrect. Use 'GeoSeries.to_crs()' to re-project geometries to a projected CRS before this operation.


c:\Users\leoni\anaconda3\lib\site-packages\shapely\measurement.py:74: RuntimeWarning:

invalid value encountered in distance

C:\Users\leoni\AppData\Local\Temp\ipykernel_20116\2288156039.py:13: UserWarning:

Geometry is in a geographic CRS. Results from 'distance' are likely incorrect. Use 'GeoSeries.to_crs()' to re-project geometries to a projected CRS before this operation.


c:\Users\leoni\anaconda3\lib\site-packages\shapely\measurement.py:74: RuntimeWarning:

invalid value encountered in distance

C:\Users\leoni\AppData\Local\Temp\ipykernel_20116\2288156039.py:13: UserWarning:

Geometry is in a geographic CRS. Results from 'distance' are likely incorrect. Use 'GeoSeries.to_crs()' to re-project geometries to a projected CRS before this operation.


c:\Users\leoni\anaconda3\lib\site-packages\shapely\measurement.py:74: RuntimeWarning:

invalid value encountered in distance

C:\Users\leoni\AppData\Local\Temp\ipykernel_20116\2288156039.py:13: UserWarning:

Geometry is in a geographic CRS. Results from 'distance' are likely incorrect. Use 'GeoSeries.to_crs()' to re-project geometries to a projected CRS before this operation.


c:\Users\leoni\anaconda3\lib\site-packages\shapely\measurement.py:74: RuntimeWarning:

invalid value encountered in distance

C:\Users\leoni\AppData\Local\Temp\ipykernel_20116\2288156039.py:13: UserWarning:

Geometry is in a geographic CRS. Results from 'distance' are likely incorrect. Use 'GeoSeries.to_crs()' to re-project geometries to a projected CRS before this operation.


c:\Users\leoni\anaconda3\lib\site-packages\shapely\measurement.py:74: RuntimeWarning:

invalid value encountered in distance

C:\Users\leoni\AppData\Local\Temp\ipykernel_20116\2288156039.py:13: UserWarning:

Geometry is in a geographic CRS. Results from 'distance' are likely incorrect. Use 'GeoSeries.to_crs()' to re-project geometries to a projected CRS before this operation.


c:\Users\leoni\anaconda3\lib\site-packages\shapely\measurement.py:74: RuntimeWarning:

invalid value encountered in distance

C:\Users\leoni\AppData\Local\Temp\ipykernel_20116\2288156039.py:13: UserWarning:

Geometry is in a geographic CRS. Results from 'distance' are likely incorrect. Use 'GeoSeries.to_crs()' to re-project geometries to a projected CRS before this operation.


c:\Users\leoni\anaconda3\lib\site-packages\shapely\measurement.py:74: RuntimeWarning:

invalid value encountered in distance

C:\Users\leoni\AppData\Local\Temp\ipykernel_20116\2288156039.py:13: UserWarning:

Geometry is in a geographic CRS. Results from 'distance' are likely incorrect. Use 'GeoSeries.to_crs()' to re-project geometries to a projected CRS before this operation.


c:\Users\leoni\anaconda3\lib\site-packages\shapely\measurement.py:74: RuntimeWarning:

invalid value encountered in distance

C:\Users\leoni\AppData\Local\Temp\ipykernel_20116\2288156039.py:13: UserWarning:

Geometry is in a geographic CRS. Results from 'distance' are likely incorrect. Use 'GeoSeries.to_crs()' to re-project geometries to a projected CRS before this operation.


c:\Users\leoni\anaconda3\lib\site-packages\shapely\measurement.py:74: RuntimeWarning:

invalid value encountered in distance

C:\Users\leoni\AppData\Local\Temp\ipykernel_20116\2288156039.py:13: UserWarning:

Geometry is in a geographic CRS. Results from 'distance' are likely incorrect. Use 'GeoSeries.to_crs()' to re-project geometries to a projected CRS before this operation.


c:\Users\leoni\anaconda3\lib\site-packages\shapely\measurement.py:74: RuntimeWarning:

invalid value encountered in distance

C:\Users\leoni\AppData\Local\Temp\ipykernel_20116\2288156039.py:13: UserWarning:

Geometry is in a geographic CRS. Results from 'distance' are likely incorrect. Use 'GeoSeries.to_crs()' to re-project geometries to a projected CRS before this operation.


c:\Users\leoni\anaconda3\lib\site-packages\shapely\measurement.py:74: RuntimeWarning:

invalid value encountered in distance

C:\Users\leoni\AppData\Local\Temp\ipykernel_20116\2288156039.py:13: UserWarning:

Geometry is in a geographic CRS. Results from 'distance' are likely incorrect. Use 'GeoSeries.to_crs()' to re-project geometries to a projected CRS before this operation.


c:\Users\leoni\anaconda3\lib\site-packages\shapely\measurement.py:74: RuntimeWarning:

invalid value encountered in distance

C:\Users\leoni\AppData\Local\Temp\ipykernel_20116\2288156039.py:13: UserWarning:

Geometry is in a geographic CRS. Results from 'distance' are likely incorrect. Use 'GeoSeries.to_crs()' to re-project geometries to a projected CRS before this operation.


c:\Users\leoni\anaconda3\lib\site-packages\shapely\measurement.py:74: RuntimeWarning:

invalid value encountered in distance

C:\Users\leoni\AppData\Local\Temp\ipykernel_20116\2288156039.py:13: UserWarning:

Geometry is in a geographic CRS. Results from 'distance' are likely incorrect. Use 'GeoSeries.to_crs()' to re-project geometries to a projected CRS before this operation.


c:\Users\leoni\anaconda3\lib\site-packages\shapely\measurement.py:74: RuntimeWarning:

invalid value encountered in distance

C:\Users\leoni\AppData\Local\Temp\ipykernel_20116\2288156039.py:13: UserWarning:

Geometry is in a geographic CRS. Results from 'distance' are likely incorrect. Use 'GeoSeries.to_crs()' to re-project geometries to a projected CRS before this operation.


c:\Users\leoni\anaconda3\lib\site-packages\shapely\measurement.py:74: RuntimeWarning:

invalid value encountered in distance

C:\Users\leoni\AppData\Local\Temp\ipykernel_20116\2288156039.py:13: UserWarning:

Geometry is in a geographic CRS. Results from 'distance' are likely incorrect. Use 'GeoSeries.to_crs()' to re-project geometries to a projected CRS before this operation.


c:\Users\leoni\anaconda3\lib\site-packages\shapely\measurement.py:74: RuntimeWarning:

invalid value encountered in distance

C:\Users\leoni\AppData\Local\Temp\ipykernel_20116\2288156039.py:13: UserWarning:

Geometry is in a geographic CRS. Results from 'distance' are likely incorrect. Use 'GeoSeries.to_crs()' to re-project geometries to a projected CRS before this operation.


c:\Users\leoni\anaconda3\lib\site-packages\shapely\measurement.py:74: RuntimeWarning:

invalid value encountered in distance

C:\Users\leoni\AppData\Local\Temp\ipykernel_20116\2288156039.py:13: UserWarning:

Geometry is in a geographic CRS. Results from 'distance' are likely incorrect. Use 'GeoSeries.to_crs()' to re-project geometries to a projected CRS before this operation.


c:\Users\leoni\anaconda3\lib\site-packages\shapely\measurement.py:74: RuntimeWarning:

invalid value encountered in distance

C:\Users\leoni\AppData\Local\Temp\ipykernel_20116\2288156039.py:13: UserWarning:

Geometry is in a geographic CRS. Results from 'distance' are likely incorrect. Use 'GeoSeries.to_crs()' to re-project geometries to a projected CRS before this operation.


c:\Users\leoni\anaconda3\lib\site-packages\shapely\measurement.py:74: RuntimeWarning:

invalid value encountered in distance

C:\Users\leoni\AppData\Local\Temp\ipykernel_20116\2288156039.py:13: UserWarning:

Geometry is in a geographic CRS. Results from 'distance' are likely incorrect. Use 'GeoSeries.to_crs()' to re-project geometries to a projected CRS before this operation.


c:\Users\leoni\anaconda3\lib\site-packages\shapely\measurement.py:74: RuntimeWarning:

invalid value encountered in distance

C:\Users\leoni\AppData\Local\Temp\ipykernel_20116\2288156039.py:13: UserWarning:

Geometry is in a geographic CRS. Results from 'distance' are likely incorrect. Use 'GeoSeries.to_crs()' to re-project geometries to a projected CRS before this operation.


c:\Users\leoni\anaconda3\lib\site-packages\shapely\measurement.py:74: RuntimeWarning:

invalid value encountered in distance

C:\Users\leoni\AppData\Local\Temp\ipykernel_20116\2288156039.py:13: UserWarning:

Geometry is in a geographic CRS. Results from 'distance' are likely incorrect. Use 'GeoSeries.to_crs()' to re-project geometries to a projected CRS before this operation.


c:\Users\leoni\anaconda3\lib\site-packages\shapely\measurement.py:74: RuntimeWarning:

invalid value encountered in distance

C:\Users\leoni\AppData\Local\Temp\ipykernel_20116\2288156039.py:13: UserWarning:

Geometry is in a geographic CRS. Results from 'distance' are likely incorrect. Use 'GeoSeries.to_crs()' to re-project geometries to a projected CRS before this operation.


c:\Users\leoni\anaconda3\lib\site-packages\shapely\measurement.py:74: RuntimeWarning:

invalid value encountered in distance

C:\Users\leoni\AppData\Local\Temp\ipykernel_20116\2288156039.py:13: UserWarning:

Geometry is in a geographic CRS. Results from 'distance' are likely incorrect. Use 'GeoSeries.to_crs()' to re-project geometries to a projected CRS before this operation.


c:\Users\leoni\anaconda3\lib\site-packages\shapely\measurement.py:74: RuntimeWarning:

invalid value encountered in distance

C:\Users\leoni\AppData\Local\Temp\ipykernel_20116\2288156039.py:13: UserWarning:

Geometry is in a geographic CRS. Results from 'distance' are likely incorrect. Use 'GeoSeries.to_crs()' to re-project geometries to a projected CRS before this operation.


c:\Users\leoni\anaconda3\lib\site-packages\shapely\measurement.py:74: RuntimeWarning:

invalid value encountered in distance

C:\Users\leoni\AppData\Local\Temp\ipykernel_20116\2288156039.py:13: UserWarning:

Geometry is in a geographic CRS. Results from 'distance' are likely incorrect. Use 'GeoSeries.to_crs()' to re-project geometries to a projected CRS before this operation.


c:\Users\leoni\anaconda3\lib\site-packages\shapely\measurement.py:74: RuntimeWarning:

invalid value encountered in distance

C:\Users\leoni\AppData\Local\Temp\ipykernel_20116\2288156039.py:13: UserWarning:

Geometry is in a geographic CRS. Results from 'distance' are likely incorrect. Use 'GeoSeries.to_crs()' to re-project geometries to a projected CRS before this operation.


c:\Users\leoni\anaconda3\lib\site-packages\shapely\measurement.py:74: RuntimeWarning:

invalid value encountered in distance

C:\Users\leoni\AppData\Local\Temp\ipykernel_20116\2288156039.py:13: UserWarning:

Geometry is in a geographic CRS. Results from 'distance' are likely incorrect. Use 'GeoSeries.to_crs()' to re-project geometries to a projected CRS before this operation.


c:\Users\leoni\anaconda3\lib\site-packages\shapely\measurement.py:74: RuntimeWarning:

invalid value encountered in distance

C:\Users\leoni\AppData\Local\Temp\ipykernel_20116\2288156039.py:13: UserWarning:

Geometry is in a geographic CRS. Results from 'distance' are likely incorrect. Use 'GeoSeries.to_crs()' to re-project geometries to a projected CRS before this operation.


c:\Users\leoni\anaconda3\lib\site-packages\shapely\measurement.py:74: RuntimeWarning:

invalid value encountered in distance

C:\Users\leoni\AppData\Local\Temp\ipykernel_20116\2288156039.py:13: UserWarning:

Geometry is in a geographic CRS. Results from 'distance' are likely incorrect. Use 'GeoSeries.to_crs()' to re-project geometries to a projected CRS before this operation.


c:\Users\leoni\anaconda3\lib\site-packages\shapely\measurement.py:74: RuntimeWarning:

invalid value encountered in distance

C:\Users\leoni\AppData\Local\Temp\ipykernel_20116\2288156039.py:13: UserWarning:

Geometry is in a geographic CRS. Results from 'distance' are likely incorrect. Use 'GeoSeries.to_crs()' to re-project geometries to a projected CRS before this operation.


c:\Users\leoni\anaconda3\lib\site-packages\shapely\measurement.py:74: RuntimeWarning:

invalid value encountered in distance

C:\Users\leoni\AppData\Local\Temp\ipykernel_20116\2288156039.py:13: UserWarning:


,UnfallID,Unfallart,Unfallschwere,Fussgänger_beteiligt,Fahrrad_beteiligt,Motorrad_beteiligt,Strassentyp,Unfallort_Lon,Unfallort_Lat,Kanton,Gemeinde,Jahr,Monat,Wochentag,Stunde,Stunde_text,geometry,Temporegime
0,2AF2FBACB62B00DAE0530A8394273CC3,Fussgängerunfall,Unfall mit Leichtverletzten,true,true,false,Nebenstrasse,2681186,1247896,ZH,0261,2016,Januar,Mittwoch,16,16h-17h,POINT (8.51365 47.37690),T50
1,2B51E1C5A119015CE0530A839427323A,Schleuder- oder Selbstunfall,Unfall mit Leichtverletzten,false,true,false,Hauptstrasse,2682739,1244360,ZH,0261,2016,Januar,Freitag,13,13h-14h,POINT (8.53356 47.34490),T50
2,2C6EC4B16319006EE0530A8394275C3E,Schleuder- oder Selbstunfall,Unfall mit Leichtverletzten,false,true,false,Nebenstrasse,2683598,1248099,ZH,0261,2016,Februar,Samstag,19,19h-20h,POINT (8.54563 47.37842),T50
3,2F5393B75558017AE0530A839427C6B4,Auffahrunfall,Unfall mit Leichtverletzten,false,false,false,Hauptstrasse,2682564,1251648,ZH,0261,2016,März,Freitag,17,17h-18h,POINT (8.53259 47.41047),T50
4,303090D5AB8300A8E0530A83942731D6,Auffahrunfall,Unfall mit Leichtverletzten,false,false,false,Hauptstrasse,2685438,1251781,ZH,0261,2016,Januar,Donnerstag,10,10h-11h,POINT (8.57069 47.41130),T50

In [42]:
unfaelle.info()

<class 'geopandas.geodataframe.GeoDataFrame'>
RangeIndex: 11689 entries, 0 to 11688
Data columns (total 18 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   UnfallID              11689 non-null  object
 1   Unfallart             11689 non-null  object
 2   Unfallschwere         11689 non-null  object
 3   Fussgänger_beteiligt  11689 non-null  object
 4   Fahrrad_beteiligt     11689 non-null  object
 5   Motorrad_beteiligt    11689 non-null  object
 6   Strassentyp           11689 non-null  object
 7   Unfallort_Lon         11689 non-null  object
 8   Unfallort_Lat         11689 non-null  object
 9   Kanton                11689 non-null  object
 10  Gemeinde              11689 non-null  object
 11  Jahr                  11689 non-null  object
 12  Monat                 11689 non-null  object
 13  Wochentag             11689 non-null  object
 14  Stunde                11689 non-null  object
 15  Stunde_text           11689 non-null  object
 16  geometry              11689 non-null  geometry
 17  Temporegime           11689 non-null  object
dtypes: geometry(1), object(17)
memory usage: 1.6+ MB

In [43]:
unfaelle['Temporegime'].value_counts()

Temporegime
T50                              7416
T30                              3384
T60                               323
T20                               179
T120                              123
T80                               112
T100                               76
T30 tagsüber, Nachtfahrverbot      69
T50 tagsüber, T30 nachts            7
Name: count, dtype: int64

In [44]:
# Erstelle eine Karte, die die Unfälle nach Temporegime einfärbt
fig = px.scatter_mapbox(unfaelle, lat=unfaelle.geometry.y, lon=unfaelle.geometry.x, color='Temporegime', zoom=10)
fig.update_layout(
    mapbox_style="open-street-map", 
    width=600,
    height=600,
    legend=dict(
        x=0.01,  # Positioniert die Legende innerhalb der Karte
        y=0.99,  # nahe dem oberen Rand
        bgcolor="rgba(255, 255, 255, 0.8)"  # Halbtransparenter Hintergrund für bessere Lesbarkeit
    )
)
fig.show()

In [46]:
# Exportiere die Unfälle mit den Tempolimits
unfaelle.to_file(r"C:\Users\leoni\Documents\HSLU\5. Semester\Informationsvisualisierung\Einzelprojekt\informationsvisualisierung-leonid-wouters\Daten\unfaelle_zuerich_2023_temporegime.json", driver='GeoJSON')